personal/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('projetos/', include('portfolio.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path

from .views import ProjetoList, comentar

urlpatterns = [
    path('', ProjetoList.as_view(), name='projetos'),
    path('<int:pk>', comentar, name='projeto'),
]

portfolio/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

user_model = get_user_model()


class Projeto(models.Model):
    titulo = models.CharField(max_length=100)
    descricao = models.TextField()
    imagem = models.ImageField(upload_to='projeto/%Y/')

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('projeto', kwargs={'pk': self.id})


class Comentario(models.Model):
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50)
    comentario = models.TextField()

    user = models.ForeignKey(user_model, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self.projeto}: {self.nome}'

    def save(self, *args, **kwargs):
        if self.user is not None:
            self.nome = self.user.username

        super().save(*args, **kwargs)

portfolio/forms.py
from django import forms

from portfolio.models import Comentario


class ComentarioForm(forms.Form):
    nome = forms.CharField(max_length=50)
    comentario = forms.CharField(widget=forms.Textarea())


class ComentarioModelForm(forms.ModelForm):
    class Meta:
        model = Comentario
        exclude = ['projeto', 'user', 'nome']

portfolio/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic import DetailView, ListView

from .forms import ComentarioForm, ComentarioModelForm
from .models import Comentario, Projeto


def teste(request):
    return HttpResponse('Ola Mundo')


def projeto_list(request):
    projetos = Projeto.objects.all()

    context = {
        'projetos': projetos
    }

    return render(request, 'projeto_list.html', context)


class ProjetoList(ListView):
    model = Projeto
#    template_name = ''
#    context_object_name = 'projetos'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['qualquer'] = 'Python'
        return context


def projeto_detail(request, pk):
    projeto = get_object_or_404(Projeto, pk=pk)

    context = {
        'projeto': projeto
    }

    return render(request, 'projeto_detail.html', context)


class ProjetoDetail(DetailView):
    model = Projeto


def comentar(request, pk):
    projeto = get_object_or_404(Projeto, pk=pk)

    if request.POST:
        form = ComentarioModelForm(request.POST)

        if form.is_valid():
            comentario = Comentario(
                projeto=projeto,
                user=request.user,
#                nome=form.cleaned_data['nome'],
                comentario=form.cleaned_data['comentario']
            )
            comentario.save()
    else:
        form = ComentarioModelForm()

    context = {
        "form": form,
        "projeto": projeto
    }

    return render(request, "portfolio/projeto_detail.html", context)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>{% block titulo_pagina %}{% endblock %}</title>
</head>
<body>
{% block conteudo %}{% endblock %}
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
-->
</body>
</html>

templates/portfolio/projeto_detail.html
{% extends "base.html" %}

{% block titulo %}Projeto: {{ projeto.titulo }}{% endblock %}

{% block conteudo %}
<div class="content">
    <h1>{{ projeto.titulo }}</h1>
    <p>{{ projeto.descricao }}</p>

    {% if request.user.is_authenticated %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Comentar">
    </form>
    {% endif %}

    <ul>
    {% for comentario in projeto.comentario_set.all %}
        <li>{{ comentario.nome }}: {{ comentario.comentario }}</li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

templates/portfolio/projeto_list.html
{% extends "base.html" %}

{% block titulo %}Projetos{% endblock %}

{% block conteudo %}
<h1>Projetos</h1>

<div class="row">

    <h2>{{ qualquer }}</h2>

    {% for projeto in projeto_list %}
    <div class="card col" style="width: 18rem;">
        <img src="{{ projeto.imagem.url }}" class="card-img-top" alt="">
        <div class="card-body">
            <h5 class="card-title">{{ projeto.titulo }}</h5>
            <p class="card-text">{{ projeto.descricao }}</p>
            <a href="{{ projeto.get_absolute_url }}" class="btn btn-primary">Detalhe</a>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock %}